- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest
- name: Start and Enable nginx
  ansible.builtin.service:
    name: nginx
    state: started      
    enabled: yes

- name: Delete directory html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
- name: Create directory html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
- name: Download and Unzip file
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html
    remote_src: yes

#Only if there us change in configuration we need to restart, ansible provides handlers for this..
- name: Copy the expense.conf
  ansible.builtin.template:
    src:  expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx
# - name: Restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted








#OUTPUT

# [ ec2-user@ip-172-31-29-250 ~/expense-ansible-roles-common ]$ ansible-playbook main.yaml -e component=frontend

# PLAY [Configuring frontend Server] ***************************************************************************************************

# TASK [Gathering Facts] ***************************************************************************************************************
# ok: [mydevops-learning.cloud]

# TASK [frontend : Install nginx] ******************************************************************************************************
# ok: [mydevops-learning.cloud]

# TASK [frontend : Start and Enable nginx] *********************************************************************************************
# ok: [mydevops-learning.cloud]

# TASK [frontend : Delete directory html] **********************************************************************************************
# changed: [mydevops-learning.cloud]

# TASK [frontend : Create directory html] **********************************************************************************************
# changed: [mydevops-learning.cloud]

# TASK [frontend : Download and Unzip file] ********************************************************************************************
# changed: [mydevops-learning.cloud]

# TASK [frontend : Copy the expense.conf] **********************************************************************************************
# changed: [mydevops-learning.cloud]

# RUNNING HANDLER [frontend : restart nginx] *******************************************************************************************
# changed: [mydevops-learning.cloud]



